default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: seeker_development

test:
  <<: *default
  database: seeker_development_test

production:
  primary:
    <<: *default
    database: <%= ENV["DB_NAME"] %>

cache:
  production:
    <<: *default
    database: <%= ENV["DB_NAME"] %>

queue:
  production:
    <<: *default
    database: <%= ENV["DB_NAME"] %>

cable:
  production:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
